steps:
- label: Build 10.15.2 Vanilla 
  command: 
    - "source ~/.bash_profile"
    - "if [[ ! $(anka show macos-vanilla-10.15) ]]; then cd packer && packer build macos-vanilla-10.15.json; fi"
- label: Build 10.15.2 CI
  command:
    - "source ~/.bash_profile"
    - "if [[ ! $(anka show macos-ci-10.15) ]]; then cd packer && packer build macos-ci-10.15.json; fi"
- label: Anka Flow CI Job
  command:
    - "whoami"
    - "pwd"
    - "env"
    - "brew list"
  plugins:
    - https://github.com/call/anka-flow-buildkite-plugin.git:v0.0.2:
        clone_source_vm: macos-ci-10.15
