steps:
  - label: Build 10.15.2 Vanilla
    command:
      - "if [[ ! $(anka show macos-vanilla-10.15) ]]; then cd packer && /Users/vao/.asdf/shims/packer build macos-vanilla-10.15.json; fi"
    agents:
      queue: water-monkey
  - label: Build 10.15.2 CI
    command:
      - "if [[ ! $(anka show macos-ci-10.15) ]]; then cd packer && /Users/vao/.asdf/shims/packer build macos-ci-10.15.json; fi"
    agents:
      queue: water-monkey
  - label: Anka Flow CI Job
    command:
      - "whoami"
      - "pwd"
      - "env"
      - "export PATH=/usr/local/bin:$PATH"
      - "/usr/local/bin/brew list"
    agents:
      queue: water-monkey
    plugins:
      - https://github.com/call/anka-flow-buildkite-plugin#v0.0.3:
          source_vm_name: macos-ci-10.15
  - label: Build 10.15.2 GSE
    command:
      - "if [[ ! $(anka show macos-gse-10.15) ]]; then cd packer && /Users/vao/.asdf/shims/packer build macos-gse-10.15.json; fi"
      - "sleep 20"
      - "/bin/bash packer/scripts/macos/enable_uamdm.sh"
      - "sleep 60"
    agents:
      queue: water-monkey
  - label: Anka Flow GSE Job
    command:
      - "whoami"
      - "pwd"
      - "which jamf"
      - "sudo jamf version"
    agents:
      queue: water-monkey
    plugins:
      - https://github.com/call/anka-flow-buildkite-plugin#v0.0.3:
          source_vm_name: macos-gse-10.15
