agent_queue: &agent_queue "iron-shark"

steps:
- label: Build 10.15.2 Vanilla 
  command: 
    - "source ~/.bash_profile"
    - "if [[ ! $(anka show macos-vanilla-10.15) ]]; then cd packer && packer build macos-vanilla-10.15.json; fi"
  agents:
    queue: *agent_queue
- label: Build 10.15.2 CI
  command:
    - "source ~/.bash_profile"
    - "if [[ ! $(anka show macos-ci-10.15) ]]; then cd packer && packer build macos-ci-10.15.json; fi"
  agents:
    queue: *agent_queue
- label: Anka Flow CI Job
  command:
    - "whoami"
    - "pwd"
    - "env"
    - "export PATH=/usr/local/bin:$PATH"
    - "/usr/local/bin/brew list"
  agents:
    queue: *agent_queue
  plugins:
    - chef/anka#v0.5.6::
        vm-name: macos-ci-10.15
        wait-network: true
